# Generated by Django 5.0 on 2024-05-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_participants', models.IntegerField(default=0, help_text='No of Members')),
                ('leader_name', models.CharField(help_text='Team Leader Name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_awareness', to='vcg.vmpps')),
            ],
            options={
                'verbose_name': 'Awareness',
                'verbose_name_plural': 'Awarenesses',
                'db_table': 'tbl_awareness',
            },
        ),
        migrations.CreateModel(
            name='AwarenessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='awareness_images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('awareness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awareness_images', to='awareness.awareness')),
            ],
            options={
                'verbose_name': 'Awareness Images',
                'verbose_name_plural': 'Awareness Images',
                'db_table': 'tbl_awareness_images',
            },
        ),
        migrations.CreateModel(
            name='AwarenessTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Team Member Name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('awareness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awareness_team', to='awareness.awareness')),
            ],
            options={
                'verbose_name': 'Awareness Team Member',
                'verbose_name_plural': 'Awareness Team Members',
                'db_table': 'tbl_awareness_team_member',
            },
        ),
    ]
