# Generated by Django 5.0 on 2024-05-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awareness',
            options={'verbose_name': 'Awareness', 'verbose_name_plural': 'Awarenesse'},
        ),
    ]
