# Generated by Django 5.0 on 2024-05-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_alter_awareness_options'),
        ('vcg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awareness',
            name='mpp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_awareness', to='vcg.vmpps'),
        ),
    ]
