# Generated by Django 5.0 on 2024-05-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_type', models.CharField(max_length=50)),
                ('created_dat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conducted By Type',
                'verbose_name_plural': 'Conducted By Types',
                'db_table': 'tbl_conducted_type',
            },
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facilitator',
                'verbose_name_plural': 'Facilitators',
                'db_table': 'tbl_facilitators',
            },
        ),
        migrations.CreateModel(
            name='MemberCompaintReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Member Complaint Reason',
                'verbose_name_plural': 'Member Complaint Reasons',
                'db_table': 'tbl_member_complaint',
            },
        ),
        migrations.CreateModel(
            name='VCGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'VCG Group',
                'verbose_name_plural': 'VCG Groups',
                'db_table': 'tbl_vcg_member',
            },
        ),
        migrations.CreateModel(
            name='VMCCs',
            fields=[
                ('mcc', models.CharField(max_length=100)),
                ('mcc_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VCG MCC',
                'verbose_name_plural': 'VCG MCCs',
                'db_table': 'tbl_vcg_mcc',
            },
        ),
        migrations.CreateModel(
            name='VMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('max_qty', models.FloatField(default=0)),
                ('cattle_bag', models.IntegerField(default=0)),
                ('mineral_bag', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'V Member',
                'verbose_name_plural': 'V Members',
                'db_table': 'tbl_vmembers',
            },
        ),
        migrations.CreateModel(
            name='ZeroDaysPourerReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Zero days pouring Reason',
                'verbose_name_plural': 'Zero days pouring Reasons',
                'db_table': 'tbl_zero_days_pouring',
            },
        ),
        migrations.CreateModel(
            name='ConductedByName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_dat', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_by_type', to='vcg.conductedbytype')),
            ],
            options={
                'verbose_name': 'Conducted By Name',
                'verbose_name_plural': 'Conducted By Names',
                'db_table': 'tbl_conducted_name',
            },
        ),
        migrations.CreateModel(
            name='VCGMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('meeting_id', models.CharField(default='', max_length=100, unique=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20)),
                ('conducted_by_fs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_fs', to='vcg.facilitator')),
                ('conducted_by_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_name', to='vcg.conductedbyname')),
                ('conducted_by_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_type', to='vcg.conductedbytype')),
            ],
            options={
                'verbose_name': 'VCG Meeting',
                'verbose_name_plural': 'VCG Meetings',
                'db_table': 'tbl_vcg_meeting',
            },
        ),
        migrations.CreateModel(
            name='VCGMeetingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='meeting_images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_images', to='vcg.vcgmeeting')),
            ],
            options={
                'verbose_name': 'VCG Meeting Images',
                'verbose_name_plural': 'VCG Meeting Images',
                'db_table': 'tbl_meeting_images',
            },
        ),
        migrations.CreateModel(
            name='VCGMemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='vcg.vcgmeeting')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_attendance', to='vcg.vcgroup')),
            ],
            options={
                'verbose_name': 'VCG Member Attendance',
                'verbose_name_plural': 'VCG Member Attendances',
                'db_table': 'tbl_member_attendance',
            },
        ),
        migrations.AddField(
            model_name='facilitator',
            name='mcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcg.vmccs'),
        ),
        migrations.AddField(
            model_name='vcgroup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='vcg.vmembers'),
        ),
        migrations.CreateModel(
            name='MemberComplaintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_complaint_reason', to='vcg.membercompaintreason')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_member_complaints', to='vcg.vcgmeeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_pouring', to='vcg.vmembers')),
            ],
            options={
                'verbose_name': 'Member Complaint Report',
                'verbose_name_plural': 'Member Complaint Reports',
                'db_table': 'tbl_member_complaint_report',
            },
        ),
        migrations.CreateModel(
            name='VMPPs',
            fields=[
                ('mpp_loc', models.CharField(max_length=100)),
                ('mpp_loc_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcc_mpps_list', to='vcg.vmccs')),
            ],
            options={
                'verbose_name': 'VCG MPP',
                'verbose_name_plural': 'VCG MPPs',
                'db_table': 'tbl_vcg_mpp',
            },
        ),
        migrations.AddField(
            model_name='vmembers',
            name='mpp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_members', to='vcg.vmpps'),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='mpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_vcg_meetings', to='vcg.vmpps'),
        ),
        migrations.CreateModel(
            name='MonthAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_collection', models.FloatField(default=0, help_text='Milk Collection (Liters/Day)')),
                ('no_of_members', models.IntegerField(default=0, help_text='No of Members')),
                ('no_of_pourers', models.IntegerField(default=0, help_text='No Of Pourers')),
                ('pourers_15_days', models.IntegerField(default=0, help_text='>=15 Days Pourers')),
                ('pourers_25_days', models.IntegerField(default=0, help_text='>=25 Days Pourers')),
                ('zero_days_pourers', models.IntegerField(default=0, help_text='Zero Days Pourers')),
                ('cattle_feed_sale', models.FloatField(default=0, help_text='Cattle Feed Sale (KG)')),
                ('mineral_mixture_sale', models.FloatField(default=0, help_text='Mineral Mixture Sale (KG)')),
                ('sahayak_recovery', models.FloatField(default=0, help_text='Sahayak Recovery (%)')),
                ('mpp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_assignment', to='vcg.vmpps')),
            ],
            options={
                'verbose_name': 'Month Assignment',
                'verbose_name_plural': 'Month Assignments',
                'db_table': 'tbl_month_assignment',
            },
        ),
        migrations.CreateModel(
            name='ZeroDaysPouringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_zero_days_pouring', to='vcg.vcgmeeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zerodays_pouring', to='vcg.vmembers')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zero_pouring_reason', to='vcg.zerodayspourerreason')),
            ],
            options={
                'verbose_name': 'Zero Days Pouring Report',
                'verbose_name_plural': 'Zero Days Pouring Reports',
                'db_table': 'tbl_zerodays_report',
            },
        ),
    ]
