# Generated by Django 5.0 on 2024-07-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='mcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitators', to='vcg.vmccs'),
        ),
    ]
