# Generated by Django 5.0 on 2024-09-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcg', '0004_eventsession_zeropourermembers_dispatchdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf', models.IntegerField(default=0, help_text='Enter the value for CF', verbose_name='CF')),
                ('mm', models.IntegerField(default=0, help_text='Enter the value for MM', verbose_name='MM')),
                ('deverming', models.IntegerField(default=0, help_text='Enter the value for Deverming', verbose_name='Deverming')),
                ('ss_utensils', models.IntegerField(default=0, help_text='Enter the value for SS Utensils', verbose_name='SS Utensils')),
                ('fodder_seeds', models.IntegerField(default=0, help_text='Enter the value for Fodder Seeds', verbose_name='Fodder Seeds')),
            ],
        ),
        migrations.AddField(
            model_name='mppvisitby',
            name='new_membership_enrolled',
            field=models.IntegerField(default=0, help_text='How many new memberships are enrolled in kashee', verbose_name='New Membership Enrolled'),
        ),
        migrations.AddField(
            model_name='nonpourermeet',
            name='zero_days_reaason',
            field=models.ForeignKey(help_text='Zero days reason for not pouring milk.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcg.zerodayspourerreason', verbose_name='Zero Days Pouring Reason'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='sahayak_code',
            field=models.CharField(blank=True, help_text='In which code sahayak pouring non-member (Not a member of Kashee MPC) milk', max_length=50, null=True, verbose_name='Sahayak Code'),
        ),
    ]
