# Generated by Django 5.0 on 2024-09-10 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcg', '0005_agriculturalproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalproducts',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was created.', verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='agriculturalproducts',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saledemands', to='vcg.eventsession'),
        ),
        migrations.AddField(
            model_name='agriculturalproducts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='compositedata',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='compositedata', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='dispatchdata',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='dispatchdata', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='formprogress',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formprogress', to='vcg.eventsession'),
        ),
        migrations.AlterField(
            model_name='maintenancechecklist',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='maintenancecheck', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='membershipapp',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='membershipapp', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='facilitator_name',
            field=models.CharField(help_text='Name of the facilitator or Area Manager.', max_length=255, verbose_name='Facilitator Name'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='mcc',
            field=models.CharField(help_text='MCC cname.', max_length=255, verbose_name='MCC'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='mpp',
            field=models.CharField(help_text='MPP code.', max_length=255, verbose_name='MPP'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='non_pourer_names',
            field=models.TextField(blank=True, help_text='Names of non-pourers required, if "Number of Non-Member Pourers" more than 0.', null=True, verbose_name='Non-Pourer Names'),
        ),
        migrations.AlterField(
            model_name='mppvisitby',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='mppvisit', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='nonpourermeet',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason is required for other "zero_days_reaason" other.', null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='nonpourermeet',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='nonpourermeet', to='vcg.eventsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='nonpourermeet',
            name='zero_days_reaason',
            field=models.ForeignKey(blank=True, help_text='Zero days reason for not pouring milk.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcg.zerodayspourerreason', verbose_name='Zero Days Pouring Reason'),
        ),
        migrations.AlterField(
            model_name='sessionvcgmeeting',
            name='session',
            field=models.ForeignKey(help_text='Associated event session.', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='vcg.eventsession', verbose_name='Session'),
        ),
    ]
