# Generated by Django 5.0 on 2024-04-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmembers',
            name='mpp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_members', to='invent_app.vmpps'),
        ),
    ]
