# Generated by Django 5.0 on 2024-04-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackcategory',
            name='department',
        ),
    ]
