# Generated by Django 5.0 on 2024-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadBranch',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('store keeper', 'STOREKEEPER'), ('finance', 'FINANCE')], max_length=20),
        ),
    ]
