# Generated by Django 5.0 on 2024-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
