# Generated by Django 5.0 on 2024-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0002_alter_vmembers_mpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcgmemberattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=10),
        ),
    ]
