# Generated by Django 5.0 on 2024-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0002_remove_feedbackcategory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerfeedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
