# Generated by Django 5.0 on 2024-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0003_alter_vcgmemberattendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCompaintReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ZeroDaysPourerReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
    ]
