# Generated by Django 5.0 on 2024-04-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0003_alter_farmerfeedback_mobile_alter_feedback_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='farmerfeedback',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
