# Generated by Django 5.0 on 2024-06-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0004_farmerfeedback_mcc_code_farmerfeedback_mcc_ex_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerfeedback',
            name='file',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
        migrations.CreateModel(
            name='FarmerFeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback_files/')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_files', to='invent_app.farmerfeedback')),
            ],
        ),
    ]
