# Generated by Django 5.0 on 2024-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0004_logo_emailconfirmation_otptoken_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
