# Generated by Django 5.0 on 2024-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0004_remove_feedback_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSopported',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(default='en-US', max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='language_icons')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'tbl_lang_supported',
            },
        ),
    ]
