# Generated by Django 5.0 on 2024-04-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0005_alter_membercompaintreason_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercomplaintreport',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_pouring', to='invent_app.vmembers'),
        ),
        migrations.AlterField(
            model_name='zerodayspouringreport',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zerodays_pouring', to='invent_app.vmembers'),
        ),
    ]
