# Generated by Django 5.0 on 2024-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0005_remove_farmerfeedback_file_remove_feedback_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfeedback',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
