# Generated by Django 5.0 on 2024-04-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0005_languagesopported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(choices=[('sahayak', 'SAHAYAK'), ('gro', 'GRO'), ('hod', 'HOD'), ('member', 'MEMBER'), ('ce', 'CE')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
