# Generated by Django 5.0 on 2024-04-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0006_alter_membercomplaintreport_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmembers',
            options={'verbose_name': 'V Member', 'verbose_name_plural': 'V Members'},
        ),
        migrations.AlterModelOptions(
            name='zerodayspourerreason',
            options={'verbose_name': 'Zero days pouring Reason', 'verbose_name_plural': 'Zero days pouring Reasons'},
        ),
        migrations.AlterModelTable(
            name='zerodayspourerreason',
            table='tbl_zero_days_pouring',
        ),
    ]
