# Generated by Django 5.0 on 2024-06-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0006_farmerfeedback_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecentFeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_feedback', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Employee Recent FeedbackLog',
                'verbose_name_plural': 'Employee Recent FeedbackLogs',
                'db_table': 'tbl_employee_feedback',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('OK', 'Ok')], default='Open', max_length=10)),
                ('feedback', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('re_message', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_forwarded_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_sent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
