# Generated by Django 5.0 on 2024-04-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0007_alter_vmembers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcgmemberattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=50),
        ),
    ]
