# Generated by Django 5.0 on 2024-04-16 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0007_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Animal Breed',
                'verbose_name_plural': 'Animal Breeds',
                'db_table': 'tbl_animal_breed',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'tbl_animal_type',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'tbl_disease',
            },
        ),
        migrations.CreateModel(
            name='MCCs',
            fields=[
                ('mcc', models.CharField(max_length=100)),
                ('mcc_code', models.CharField(default='EX_CODE', max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'MCC',
                'verbose_name_plural': 'MCCs',
                'db_table': 'tbl_mcc',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'tbl_medicines',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('FarmerId', models.IntegerField(blank=True, null=True)),
                ('FarmerCode', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('FullName', models.CharField(max_length=255)),
                ('FatherName', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('PlantID', models.IntegerField(blank=True, null=True)),
                ('PlantCode', models.CharField(blank=True, max_length=20, null=True)),
                ('PlantName', models.CharField(max_length=100)),
                ('MccID', models.IntegerField(blank=True, null=True)),
                ('MccCode', models.CharField(blank=True, max_length=20, null=True)),
                ('MccName', models.CharField(max_length=100)),
                ('MstCenterCode', models.IntegerField()),
                ('BmcName', models.CharField(max_length=100)),
                ('SocietyCode', models.IntegerField(blank=True, null=True)),
                ('SocietyName', models.CharField(max_length=100)),
                ('CompanyId', models.IntegerField(blank=True, null=True)),
                ('AddressLine1', models.CharField(blank=True, max_length=255, null=True)),
                ('AddressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('VillageId', models.IntegerField(blank=True, null=True)),
                ('DistrictId', models.IntegerField(blank=True, null=True)),
                ('DistrictName', models.CharField(max_length=100)),
                ('StateId', models.IntegerField(blank=True, null=True)),
                ('StateName', models.CharField(max_length=100)),
                ('VillageName', models.CharField(max_length=100)),
                ('IsRegistered', models.BooleanField(default=False)),
                ('RegistrationDate', models.DateTimeField(blank=True, null=True)),
                ('OTP', models.CharField(blank=True, max_length=255, null=True)),
                ('EncToken', models.TextField(blank=True, null=True)),
                ('DefaultLanguage', models.IntegerField(blank=True, null=True)),
                ('otpsms', models.TextField(blank=True, null=True)),
                ('opt_status', models.CharField(blank=True, max_length=255, null=True)),
                ('smsurl', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'tbl_members',
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'db_table': 'tbl_animal_symptoms',
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_animals', to='invent_app.animalbreed')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_animals', to='invent_app.member')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'tbl_animals',
            },
        ),
        migrations.AddField(
            model_name='animalbreed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='invent_app.animaltype'),
        ),
        migrations.CreateModel(
            name='AnimalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment', to='invent_app.animals')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments_done', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_treatment', to='invent_app.disease')),
            ],
            options={
                'verbose_name': 'AnimalTreatment',
                'verbose_name_plural': 'AnimalTreatments',
                'db_table': 'tbl_animal_treatments',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='medicines',
            field=models.ManyToManyField(to='invent_app.medicine'),
        ),
        migrations.CreateModel(
            name='MPPs',
            fields=[
                ('mpp_loc', models.CharField(max_length=100)),
                ('mpp_loc_code', models.CharField(default='EX_CODE', max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpps', to='invent_app.mccs')),
            ],
            options={
                'verbose_name': 'MPP',
                'verbose_name_plural': 'MPPs',
                'db_table': 'tbl_mpp',
            },
        ),
    ]
