# Generated by Django 5.0 on 2024-04-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0008_alter_vcgmemberattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcgmemberattendance',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vcg_attendance', to='invent_app.vcgroup'),
        ),
    ]
