# Generated by Django 5.0 on 2024-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0008_alter_employeerecentfeedbacklog_recent_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefeedback',
            name='feedback',
            field=models.CharField(max_length=200),
        ),
    ]
