# Generated by Django 5.0 on 2024-03-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='department',
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_category', to='invent_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent_app.feedbackcategory'),
        ),
    ]
