# Generated by Django 5.0 on 2024-04-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0009_alter_vcgmemberattendance_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcgmeeting',
            name='conducted_by',
        ),
        migrations.RemoveField(
            model_name='vcgmeetingimages',
            name='attendance',
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='conducted_by_fs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_fs', to='invent_app.facilitator'),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='conducted_by_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_name', to='invent_app.conductedbyname'),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='conducted_by_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_meeting_conducted_type', to='invent_app.conductedbytype'),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='meeting_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vcgmeeting',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcgmeetingimages',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_images', to='invent_app.vcgmeeting'),
        ),
        migrations.AddField(
            model_name='vcgmemberattendance',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='invent_app.vcgmeeting'),
        ),
        migrations.AlterField(
            model_name='vcgmemberattendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcg_attendance', to='invent_app.vcgroup'),
        ),
    ]
