# Generated by Django 5.0 on 2024-04-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0010_remove_vcgmeeting_conducted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcgmeeting',
            name='mpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_vcg_meetings', to='invent_app.vmpps'),
        ),
    ]
