# Generated by Django 5.0 on 2024-04-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0011_alter_vcgmeeting_mpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_collection', models.FloatField(default=0, help_text='Milk Collection (Liters/Day)')),
                ('no_of_members', models.IntegerField(default=0, help_text='No of Members')),
                ('no_of_pourers', models.IntegerField(default=0, help_text='No Of Pourers')),
                ('pourers_15_days', models.IntegerField(default=0, help_text='>=15 Days Pourers')),
                ('pourers_25_days', models.IntegerField(default=0, help_text='>=25 Days Pourers')),
                ('zero_days_pourers', models.IntegerField(default=0, help_text='Zero Days Pourers')),
                ('cattle_feed_sale', models.FloatField(default=0, help_text='Cattle Feed Sale (KG)')),
                ('mineral_mixture_sale', models.FloatField(default=0, help_text='Mineral Mixture Sale (KG)')),
                ('sahayak_recovery', models.FloatField(default=0, help_text='Sahayak Recovery (%)')),
                ('mpp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_assignment', to='invent_app.vmpps')),
            ],
            options={
                'verbose_name': 'Month Assignment',
                'verbose_name_plural': 'Month Assignments',
                'db_table': 'tbl_month_assignment',
            },
        ),
    ]
