# Generated by Django 5.0 on 2024-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0012_monthassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmembers',
            name='cattle_bag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vmembers',
            name='mineral_bag',
            field=models.IntegerField(default=0),
        ),
    ]
