# Generated by Django 5.0 on 2024-04-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0013_vmembers_cattle_bag_vmembers_mineral_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcgmeeting',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20),
        ),
    ]
