# Generated by Django 5.0 on 2024-05-04 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0016_cattlecasestatus_cattlecasetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awareness',
            name='mpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_awareness', to='invent_app.vmpps'),
        ),
    ]
