# Generated by Django 5.0 on 2024-05-04 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cattle Type',
                'verbose_name_plural': 'Cattle Types',
                'db_table': 'tbl_animal_type',
            },
        ),
        migrations.CreateModel(
            name='CattleCaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Case Status',
                'verbose_name_plural': 'Case Statuses',
                'db_table': 'tbl_cattle_case_status',
            },
        ),
        migrations.CreateModel(
            name='CattleCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special'), ('Operational', 'Operational')], default='Normal', max_length=20)),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
                'db_table': 'tbl_cattle_case_type',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCattleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_status', models.CharField(choices=[('Milking', 'Milking'), ('Pregnant', 'Pregnant'), ('Dry Cattle', 'Dry Cattle')], max_length=20)),
            ],
            options={
                'verbose_name': 'Diagnosis Cattle Status',
                'verbose_name_plural': 'Diagnosis Cattle Statuses',
                'db_table': 'tbl_diagnosis_status',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Route',
                'verbose_name_plural': 'Diagnosis Routes',
                'db_table': 'tbl_diagnosis_route',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'tbl_animal_disease',
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('unit_of_quantity', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Medicine Category',
                'verbose_name_plural': 'Medicine Categories',
                'db_table': 'tbl_medicine_category',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('FarmerId', models.IntegerField(blank=True, null=True)),
                ('FarmerCode', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('FullName', models.CharField(max_length=255)),
                ('FatherName', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('PlantID', models.IntegerField(blank=True, null=True)),
                ('PlantCode', models.CharField(blank=True, max_length=20, null=True)),
                ('PlantName', models.CharField(max_length=100)),
                ('MccID', models.IntegerField(blank=True, null=True)),
                ('MccCode', models.CharField(blank=True, max_length=20, null=True)),
                ('MccName', models.CharField(max_length=100)),
                ('MstCenterCode', models.IntegerField()),
                ('BmcName', models.CharField(max_length=100)),
                ('SocietyCode', models.IntegerField(blank=True, null=True)),
                ('SocietyName', models.CharField(max_length=100)),
                ('CompanyId', models.IntegerField(blank=True, null=True)),
                ('AddressLine1', models.CharField(blank=True, max_length=255, null=True)),
                ('AddressLine2', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('VillageId', models.IntegerField(blank=True, null=True)),
                ('DistrictId', models.IntegerField(blank=True, null=True)),
                ('DistrictName', models.CharField(max_length=100)),
                ('StateId', models.IntegerField(blank=True, null=True)),
                ('StateName', models.CharField(max_length=100)),
                ('VillageName', models.CharField(max_length=100)),
                ('IsRegistered', models.BooleanField(default=False)),
                ('RegistrationDate', models.DateTimeField(blank=True, null=True)),
                ('OTP', models.CharField(blank=True, max_length=255, null=True)),
                ('EncToken', models.TextField(blank=True, null=True)),
                ('DefaultLanguage', models.IntegerField(blank=True, null=True)),
                ('otpsms', models.TextField(blank=True, null=True)),
                ('opt_status', models.CharField(blank=True, max_length=255, null=True)),
                ('smsurl', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'tbl_members',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'tbl_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'db_table': 'tbl_animal_symptoms',
            },
        ),
        migrations.CreateModel(
            name='TAGType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TAG Type',
                'verbose_name_plural': 'TAG Types',
                'db_table': 'tbl_tag_type',
            },
        ),
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='veterinary.animaltype')),
            ],
            options={
                'verbose_name': 'Cattle Breed',
                'verbose_name_plural': 'Cattle Breeds',
                'db_table': 'tbl_animal_breed',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_short_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'tbl_user_bank_account',
            },
        ),
        migrations.CreateModel(
            name='CaseEntry',
            fields=[
                ('address', models.CharField(default='', max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('case_no', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('applied_by_ext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_by_ext', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Entry',
                'verbose_name_plural': 'Case Entries',
                'db_table': 'tbl_case_entries',
            },
        ),
        migrations.CreateModel(
            name='CaseReceiverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('case_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_logs', to='veterinary.caseentry')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Receiver Log',
                'verbose_name_plural': 'Case Receiver Logs',
                'db_table': 'tbl_case_reciever_logs',
            },
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_animals', to='veterinary.animalbreed')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_animals', to='veterinary.member')),
                ('tag_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_animals', to='veterinary.tagtype')),
            ],
            options={
                'verbose_name': 'Cattle',
                'verbose_name_plural': 'Cattles',
                'db_table': 'tbl_cattle',
            },
        ),
        migrations.AddField(
            model_name='caseentry',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_cases', to='veterinary.cattle'),
        ),
        migrations.AddField(
            model_name='caseentry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.cattlecasestatus'),
        ),
        migrations.CreateModel(
            name='CattleTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20)),
                ('tagging_date', models.DateField()),
                ('cattle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_tagged', to='veterinary.cattle')),
            ],
            options={
                'verbose_name': 'Cattle Tagging',
                'verbose_name_plural': 'Cattle Taggings',
                'db_table': 'tbl_cattle_tagging',
            },
        ),
        migrations.CreateModel(
            name='AnimalDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_production', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('case_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_entry_diagnosis', to='veterinary.caseentry')),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.cattlecasetype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.diagnosiscattlestatus')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.disease')),
            ],
            options={
                'verbose_name': 'Animal Diagnosis',
                'verbose_name_plural': 'Animal Diagnosis',
                'db_table': 'tbl_animal_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expiary_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('recommended_for_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_medicines', to='veterinary.disease')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'tbl_medicine',
            },
        ),
        migrations.CreateModel(
            name='AnimalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('case_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment', to='veterinary.caseentry')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.diagnosisroute')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.medicine')),
            ],
            options={
                'verbose_name': 'Animal Treatment',
                'verbose_name_plural': 'Animal Treatments',
                'db_table': 'tbl_animal_treatments',
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_medicines', to='veterinary.disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Stock',
                'verbose_name_plural': 'Medicine Stock',
                'db_table': 'tbl_medicine_stock',
            },
        ),
        migrations.CreateModel(
            name='DoctorMedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_stocks', to=settings.AUTH_USER_MODEL)),
                ('medicine_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.medicinestock')),
            ],
            options={
                'verbose_name': 'Doctor Medicine Stock',
                'verbose_name_plural': 'Doctor Medicine Stocks',
                'db_table': 'tbl_doc_medicine_stock',
            },
        ),
        migrations.AddField(
            model_name='caseentry',
            name='applied_by_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_cases', to='veterinary.member'),
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='online_payment', serialize=False, to='veterinary.paymentmethod')),
                ('gateway_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Online Payment Method',
                'verbose_name_plural': 'Online Payment Methods',
                'db_table': 'tbl_online_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='CasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('case_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='veterinary.caseentry')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.paymentmethod')),
            ],
            options={
                'verbose_name': 'Case Payment',
                'verbose_name_plural': 'Case Payments',
                'db_table': 'tbl_case_payments',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='symptom_disease', to='veterinary.symptoms'),
        ),
        migrations.CreateModel(
            name='DiagnosisSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_symptoms', to='veterinary.animaldiagnosis')),
                ('symptom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary.symptoms')),
            ],
            options={
                'verbose_name': 'Animal Diagnosis',
                'verbose_name_plural': 'Animal Diagnosis',
                'db_table': 'tbl_animal_diagnosis_symp',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.cattlecasetype')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'tbl_time_slot',
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_travelled', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('case_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to='veterinary.caseentry')),
            ],
            options={
                'verbose_name': 'Travel Record',
                'verbose_name_plural': 'Travel Records',
            },
        ),
    ]
