# Generated by Django 5.0 on 2024-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosissymptoms',
            options={'verbose_name': 'Animal Diagnosis Symptom', 'verbose_name_plural': 'Animal Diagnosis Symptoms'},
        ),
        migrations.AlterField(
            model_name='cattletagging',
            name='tagging_date',
            field=models.DateField(auto_now=True),
        ),
    ]
