# Generated by Django 5.0 on 2024-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_alter_diagnosissymptoms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='FarmerId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
