# Generated by Django 5.0 on 2024-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_animalbreed_sync_animaldiagnosis_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
