# Generated by Django 5.0 on 2024-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0007_rename_price_timeslot_normal_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('milkbillpayment', 'Milk Bill Payment')], max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
    ]
