# Generated by Django 5.0 on 2024-06-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcg', '0001_initial'),
        ('veterinary', '0008_alter_paymentmethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='AddressLine1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='AddressLine2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='BmcName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='City',
        ),
        migrations.RemoveField(
            model_name='member',
            name='CompanyId',
        ),
        migrations.RemoveField(
            model_name='member',
            name='EmailAddress',
        ),
        migrations.RemoveField(
            model_name='member',
            name='EncToken',
        ),
        migrations.RemoveField(
            model_name='member',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='MccCode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='MccID',
        ),
        migrations.RemoveField(
            model_name='member',
            name='MccName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='MstCenterCode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='member',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='PlantCode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='PlantID',
        ),
        migrations.RemoveField(
            model_name='member',
            name='PlantName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='SocietyCode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='SocietyName',
        ),
        migrations.AddField(
            model_name='member',
            name='mpp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcg.vmpps'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
